# Generated by Django 2.2.5 on 2021-02-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210219_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('other', 'other'), ('female', 'female')], max_length=10),
        ),
    ]
