# Generated by Django 2.2.5 on 2021-02-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='beths',
            new_name='baths',
        ),
    ]
